name: Content As Configuration
description: Allows content entities to be exported/imported as configuration.
package: Structure
type: module
php: 7.4
core_version_requirement: ^9.3 || ^10
dependencies:
  - drupal:block_content
  - drupal:menu_link_content
  - drupal:taxonomy

# Information added by Drupal.org packaging script on 2022-10-06
version: '1.0.10'
project: 'content_as_config'
datestamp: 1665066746
